language: java
jdk:
  - openjdk7
os:
  - linux
cache:
  directories:
    - ~/.m2/repository
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P travis
script:
  - mvn test -B -P travis -Dmaven-surefire-plugin.arguments='-Xmx512m -XX:MaxPermSize=256m'
after_success:
  - mvn clean test cobertura:cobertura coveralls:report -B -P travis -DrepoToken=${COVERALLS_REPO_TOKEN} -Dmaven-surefire-plugin.arguments='-Xmx512m -XX:MaxPermSize=256m'
before_deploy:
  - travis/before-deploy.sh
deploy:
  provider: script
  script: travis/deploy.sh
  skip_cleanup: true
after_deploy:
  - travis/after-deploy.sh
