language: java
jdk:
  - openjdk8
os:
  - linux
cache:
  directories:
    - ~/.m2/repository
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --quiet --batch-mode --show-version  --activate-profiles coveralls
script:
  - mvn package jacoco:report coveralls:report --batch-mode --activate-profiles coveralls -DrepoToken=${COVERALLS_REPO_TOKEN} -Dtest.arguments='-Xmx512m -XX:MaxPermSize=256m'
