language: java
jdk:
  - openjdk7
os:
  - linux
dist: trusty
cache:
  directories:
    - ~/.m2/repository
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P travis
script:
  - mvn clean test jacoco:report coveralls:report -B -P travis -DrepoToken=${COVERALLS_REPO_TOKEN} -Dtest.arguments='-Xmx512m -XX:MaxPermSize=256m'
before_deploy:
  - travis/before-deploy.sh
deploy:
  - provider: script
    script: travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true
after_deploy:
  - travis/after-deploy.sh
